### ISSUE TITLE
Meta Rollback Issue

### ISSUE THREAD

**Issue by wycats** [emberjs/data#1288]
- [ ] Async and rollback (#1283)
- [x] Resetting after failure (#1271)
- [ ] Rollback and invalid (#1354)

I'll be working on enhanced rollback semantics and tracking the originating issues here.
