### ISSUE TITLE
1.0 blockers for Tomhuda to review:

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3298]
**Simple:** should take 1-8 minutes of discussion
- [x]  Consider renaming rollback to rollbackAttributes emberjs/data#3273
- [x] Consider changing `isDirty` flag to something like `hasDirtyAttributes` https://github.com/emberjs/data/issues/3299
- [x] Considering moving store.filter into an addon #3274 
- [x] Consider renaming the serializer attrs hash  #3186
- [x] Consider renaming DS.Snapshot - emberjs/data#3285
- [x] Confirm that this is the right thing to do: https://github.com/emberjs/data/issues/3220 waiting on senor @tomdale 

**Medium Complexity:** should not take more than 5-15 minutes
- [x] Don't unload records that are confirmed deleted #3295
- [x] Unload issue with relationships   https://github.com/emberjs/data/issues/3296
- [x] Store.query/queryRecord options behavior https://github.com/emberjs/data/issues/3297
- [x] Only support `service:store` (`app/services/store.js`) for custom stores. https://github.com/emberjs/data/pull/3286

**Comment by igorT** [comment]
@wycats @tomdale please advise

**Comment by wycats** [comment]
> Consider renaming rollback to rollbackAttributes

Works for me.

> Consider changing isDirty flag to something like areAttributesDirty

Works for me.

(do not break the old names, even for 2.0, though)

> Considering moving store.filter into an addon

Good idea. It feels risky to commit to the API right now.

> Consider renaming the serializer attrs hash
> Consider renaming DS.Snapshot

What are the best options?

> Confirm that this is the right thing to do: #3220

Can confirm. @tomdale should check me.

**Comment by bmac** [comment]
Ping @tomdale and @wycats. Would love to get your take on https://github.com/emberjs/data/pull/3286.

The Executive summary is:

Right now Ember Data supports 3 namespaces where you can define the store `store:main`, `store:application` and `service:store`. I want to reduce this to 1 place for Ember Data 2.0 because it simplifies our initializer code and if a user were to define a custom store for more then 1 of those namespaces it can result in multiple stores instances in their app which is confusing to debug.

I'd like to recommend defining a custom store as `service:store` (`app/services/store.js`) as the path going forward. Is this a good idea/bad idea?

**Comment by runspired** [comment]
> Considering moving store.filter into an addon

Heartily support of this, it would also show a pattern for extending ember-data features.  For instance, I currently crudely add methods to store for lookups based on non-ID keys (unique or just simple K=>V matching) e.g.

```
/**
     * @method getByKey
     *
     * @param typeName
     * @param key
     * @param value
     * @returns {*} A single or array of records from store if available
     */
    Store.getByKey = function getByKey(typeName, key, value) {

      return Store.filter(typeName, function (record) {
        return record.get(key) === value;
      }).then(function (matches) {
        if (matches.get('length')) {
          return matches;
        }
        return null;
      });
    };


    /**
     * @method getByUniqueKey | return a record based on a unique key
     *
     * @param typeName
     * @param key
     * @param value
     * @returns {*} A single record from store if only one exists for the key, else null
     */
    Store.getByUniqueKey = function getByUniqueKey(typeName, key, value) {

      return Store.filter(typeName, function filterKnownRecords(record) {
        return record.get(key) === value;
      }).then(function (matches) {
        assert("You looked up an item in the store by unique key '" + key + "' that was not a unique value '" + value + "'.", matches.get('length') <= 1);
        if (matches.get('length') === 1) {
          return matches.objectAt(0);
        }
        return null;
      });
    };


    /**
     * @method findByKey
     *
     * @param typeName
     * @param key
     * @param value
     * @returns {*} A single or array of records from store if available, a single or array of records from server if not
     */
    Store.findByKey = function findByKey(typeName, key, value) {

      return Store.filter(typeName, function filterKnownRecords(record) {
        return record.get(key) === value;
      }).then(function (matches) {
        if (matches.get('length')) {
          return matches;
        }
        var query = {};
        query[key] = value;
        return Store.find(typeName, query).then(function (records) {
          return records;
        });
      });
    };


    /**
     * @method findByUniqueKey
     *
     * @param typeName
     * @param key
     * @param value
     * @returns {*} A single or array of records from store if available, a single or array of records from server if not
     *
     * TODO add assertions for uniqueness
     */
    Store.findByUniqueKey = function findByUniqueKey(typeName, key, value) {

      return Store.filter(typeName, function filterKnownRecords(record) {
        return record.get(key) === value;
      }).then(function (matches) {
        assert("You looked up an item in the store by unique key '" + key + "' that was not a unique value '" + value + "'.", matches.get('length') <= 1);
        if (matches.get('length')) {
          return matches.objectAt(0);
        }
        var query = {};
        query[key] = value;
        return Store.find(typeName, query).then(function (records) {
          assert("You looked up an item from the server by unique key '" + key + "' that was not a unique value '" + value + "'.", records.get('length') <= 1);
          if (records.get('length')) {
            return records.objectAt(0);
          }
          return null;
        });
      });
    };
```

**Comment by tomdale** [comment]
> > Confirm that this is the right thing to do: #3220
> Can confirm. @tomdale should check me.

Confirm
