### ISSUE TITLE
Shipping 1.13 checklist

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3320]
- [x] make IE work @fivetanley 
- [x] move store.filter into an addon @fivetanley   https://github.com/emberjs/data/issues/3274
- [x] Deprecation if id is Model in deserializeRecordId   https://github.com/emberjs/data/pull/3279 itsmike is following up
- [x] Deprecate pushMany https://github.com/emberjs/data/issues/3246
- [x] Move active model adapter into an addon @fivetanley 
- [x] errors object cc @tchak 
- [x] find methods refactor, @bmac how are we doing here?
- [x] deprecate sync relationships
- [x] Enable `ds-new-serializer-api` feature flag #3337
- [x] deprecate non json api payloads, related https://github.com/abuiles/ember-watson/issues/42 @bmac 
- [x] tell people who use default rest serializer/adapter to have to manually select it @wecc 
- [x] hasDirtyAttributes @bmac
- [x] push deprecations @bmac

**Comment by bmac** [comment]
For the find methods refactor, I think we have 5 branches to merge then we are done.
Allow the store to pass adapter options to the adapter https://github.com/emberjs/data/pull/3310

`store.queryRecord` https://github.com/emberjs/data/pull/2584

Rename adapter and serializer methods to match the new store methods https://github.com/emberjs/data/pull/3306


Deprecate fetch and replace it with store.findRecord(type, id, { reload: true}) https://github.com/emberjs/data/pull/3312




New adapter hooks, `shouldReloadRecord` `shouldBackgroundReloadRecord` https://github.com/bmac/data/tree/should-reload
