### ISSUE TITLE
[Meta Issue] Shipping 2.0 beta.1 checklist

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3321]
- [x] delete record recordArrays breaking change #3539
- [x] turn on async by default #3488
- [ ] write blog posts
- [x] remove deprecated code
    - [x] Snapshot deprecations #3443
    - [x] Model deprecations #3442
    - [x] ManyArray deprecations #3441
    - [x] RESTSerializer deprecations #3440 
    - [x] RESTAdapter deprecations #3439
    - [x] BuildURLMixin deprecations #3438 
    - [x] Store/Finders deprecations #3469
    - [x] Container deprecations #3489
- [x] Make JSONAPIAdapter the default one #3487

descoped:
- [ ] Namespace Query https://github.com/emberjs/data/pull/3459
- [ ] references in master

**Comment by wecc** [comment]
Since we're now on the same release schedule as Ember that means Ember Data 2.0 is to be released Jul 24th. There won't be a lot of new features (if any) in 2.0 but we also need to remove all deprecated code and improve the docs for many of the things we added in 1.13.

I would like propose a target date of Ember Data 2.0 Beta 1 at latest Jul 12th to give both us and Ember Data users some time to fix whatever we might have missed.

**Comment by bmac** [comment]
2.0 beta.1 shipped long ago. Closing this issue.
