### ISSUE TITLE
[Meta Issue] Shipping 2.0 checklist

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3322]
Things that need to happen after 2.0beta but before 2.0 and preferably soon to help people migrate

- [x] https://github.com/abuiles/ember-watson/issues/40
- [ ] https://github.com/abuiles/ember-watson/issues/42
- [ ] Initial implementation of @teddyzeenny inspector tab for serialization
- [ ] remove deprecated stuff
- [ ] Write updated guides - @tomdale @locks and @wycats 
- [ ] Merge updated guides - @locks 
- [ ] new build system does not prepend license #2753

**Comment by tomdale** [comment]
@locks I added you as the responsible party for making sure updated guides get merged for the 2.0 release.

**Comment by bmac** [comment]
2.0 has shipped. Closing this issue.

**Comment by wycats** [comment]
:raised_hands:
