### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by pangratz** [emberjs/data#4238]
- [x] add section about prefixing commits, similar to [the one in ember.js](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#commit-tagging) (added in #4244 by @courajs :sparkles: )
- [x] add ember-twiddles for easier reporting of a bug (setup using pretender) (added in #4716 by @pete-the-pete)
- [ ] add note about RFC for requesting a feature instead of opening issue on emberjs/data
  - [x] implement new feature using feature flags (see https://github.com/emberjs/data/issues/4238#issuecomment-198482078, added in #4327 by @sbatson5)
- [x] add section about tests for `assert` / `warn` to use [`testInDebug`](https://github.com/emberjs/data/pull/4223) so they are skipped when testing in production environment (added in #4240 by @courajs :rocket: )

**Comment by courajs** [comment]
Can we just copy in the section on commit prefixing (and credit at the end)? Are there any differences?

**Comment by pangratz** [comment]
> Can we just copy in the section on commit prefixing (and credit at the end)? Are there any differences?

They are basically the same. I think it is ok to copy them (cc @rwjblue @bmac).

**Comment by courajs** [comment]
- [ ] Add section about wrapping new feature work in a feature flag (?)

**Comment by pete-the-pete** [comment]
can someone describe the work involved with?:
- [ ] add ember-twiddles for easier reporting of a bug (setup using pretender)

**Comment by courajs** [comment]
@pete-the-pete I believe this involves updating the jsbins/jsfiddle linked in [Reporting a Bug](https://github.com/emberjs/data/blob/master/CONTRIBUTING.md#reporting-a-bug) to
- Use [ember twiddle](https://ember-twiddle.com) instead of jsbin/fiddle
- Use [pretender](https://github.com/pretenderjs/pretender) instead of [mockjax](https://github.com/jakerella/jquery-mockjax)

Although I'd ask @pangratz to weigh in on why pretender is a better choice than mockjax - it's not obvious to me.

**Comment by Dan-Ste** [comment]
@pangratz There is still need help? I'm a beginner in OSS and want to make my first PR :)

**Comment by wecc** [comment]
From #4362 re Ember Twiddle:

> The reporting a bug section has js bins etc but Ember Twiddle can be alot easier to use. @pangratz had a basic one https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8/copy?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs that I found easy to play with and add to.
