### ISSUE TITLE
reference unification TODO

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#4358]
For @wycats after Railsconf.
- [ ] Revisit [Reference Unification](https://github.com/emberjs/rfcs/pull/57/files)
- [ ] Better ergonomics one time data
- [ ] Hooks for something updated / "freshening" process
- [ ] Other stuff? (feel free to edit)

**Comment by pangratz** [comment]
re `Hooks for something updated / "freshening" process`, there is an initial RFC about that at emberjs/rfcs#123.

**Comment by stefanpenner** [comment]
This isn't terribly actionable, will gladly reopen with additional information. But either way it seems to be more RFC material.
