### ISSUE TITLE
This project appears to introduce 6660 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#4492]
own files that may not be needed:
- [x] bin 9 #4493
- [x] docs 5 #4493

---

deps we may want to investigate
node_modules 6414
- [x] amd-name-resolver 13 https://github.com/chadhietala/amd-name-resolver/pull/8
- [x] babel-plugin-feature-flags 80 https://github.com/ember-cli/babel-plugin-feature-flags/pull/11
- [x] babel-plugin-filter-imports 33 https://github.com/ember-cli/babel-plugin-filter-imports/pull/9
- [ ] broccoli-babel-transpiler 4864 https://github.com/babel/broccoli-babel-transpiler/issues/90
- [ ] broccoli-file-creator 545 https://github.com/rwjblue/broccoli-file-creator/issues/6
- [x] broccoli-merge-trees 543 https://github.com/broccolijs/broccoli-merge-trees/issues/47
- [ ] chalk 43
- [ ] ember-cli-path-utils 3
- [x] ember-cli-string-utils 3
- [ ] ember-cli-test-info 3
- [x] ember-cli-version-checker 51 https://github.com/rwjblue/ember-cli-version-checker/pull/18
- [ ] ember-inflector 27
- [x] exists-sync 8 https://github.com/ember-cli/exists-sync/pull/3
- [x] git-repo-info 134 https://github.com/rwjblue/git-repo-info/issues/21
- [ ] inflection 10
- [ ] npm-git-info 18
- [ ] semver 8
- [ ] silent-error 25
