### ISSUE TITLE
QUnit Blueprints Quest Issue

### ISSUE THREAD

**Issue by alexander-alvarez** [emberjs/data#5292]
__Background__
https://github.com/emberjs/ember.js/issues/15933

__Tasks__
- [x] (:lock: @alexander-alvarez) Extend [test-framework detector](https://github.com/emberjs/data/blob/master/blueprints/test-framework-detector.js) to use rfc-232 style generators where applicable.
- [x] Add `<type>-test`  "simplified QUnit" blueprints
  - [x] (:lock: @alexander-alvarez) adapter-test
  - [x] (:lock: @alexander-alvarez) model-test
  - [x] (:lock: @alexander-alvarez) serializer-test
  - [x] (:lock: @alexander-alvarez) transform-test
- [ ] Extract the above tests blueprints into a standalone polyfill addon (similar to https://github.com/alexander-alvarez/ember-qunit-nested-module-blueprints-polyfill but for ember-data)

---
To pick up one of these items, please comment below and we'll update the checklist with :lock: @your-name-here...

**Comment by alexander-alvarez** [comment]
https://github.com/alexander-alvarez/data/compare/node-test-cleanups...alexander-alvarez:test-framework-detectors-fixup is ready to go once https://github.com/emberjs/data/pull/5293 is merged

**Comment by rwjblue** [comment]
The first couple of items are landed. The others are up for grabs...

**Comment by rwjblue** [comment]
@alexander-alvarez - I believe the main blueprint types have been done, and all thats left is the polyfill addon. Can you confirm?

**Comment by alexander-alvarez** [comment]
@rwjblue yup :+1:

**Comment by runspired** [comment]
@alexander-alvarez what remains here?

**Comment by alexander-alvarez** [comment]
@runspired  Just the last item
> Extract the above tests blueprints into a standalone polyfill addon

**Comment by rwjblue** [comment]
TBH, I think this is probably fine to leave off. At the time we needed a polyfill addon because 3.0 was a ways off, now its out (as is 3.1).
