### ISSUE TITLE
[META QUEST] Request for Community Help - RecordData!

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5618]
# RecordData!

The `EmberData` team needs your help!

[`RecordData RFC #293`](https://github.com/emberjs/rfcs/pull/293) brings a much needed codification to the internals of `ember-data`, giving addon developers needed API access with more confidence and stability while making many commonly requested features (improved dirty-tracking, fragments, alternative Models) possible or easier to be implemented in addon-land.

Beginning in `3.3 canary` (which became `3.4`), we've been using a build-time flag to allow us to build and run all of ember-data's tests against both the old world and the new world. We are now ready to take the next step, and bring this feature into `3.5 beta` for testing against real-world applications.

## A Quick Note on 3.4 LTS

Until now, there has never been an official `ember-data` LTS release. `3.4` is our first LTS candidate, and we will be following the LTS practices and timeline laid out by `emberjs`.  This means that in 6 weeks, `3.4` will advance to `LTS`. Bugfixes that we are targeting for LTS support are tagged as [lts-target](https://github.com/emberjs/data/labels/lts-target).

## Stability

Landing a major refactor of the internals of `ember-data` does not come without risks. Those risks include:

 - Unintended changes to public APIs
 - Removal or alteration of intimate APIs
 - Breaking community addons that depend upon intimate API
 - Breaking community addons that depend upon public APIs that change in unexpected ways

We're [committed](https://discuss.emberjs.com/t/ember-data-3-2-x-3-3-x/15201) to improving the stability of `ember-data`, even as we embark on this exciting new journey. In addition to a dedication to steadily expanding and improving our test suite, we recently we landed a number of PRs to help both us and others improve the stability experience when using `ember-data`

- [Rendering](https://github.com/emberjs/data/pull/5492)[Tests](https://github.com/emberjs/data/pull/5566)
- [Destroyed Store Assertions](https://github.com/emberjs/data/pull/5605)
- [Async Leak Detection and await settled() support](https://github.com/emberjs/data/pull/5545)
- [External Partner tests](https://github.com/emberjs/data/pull/5567)
- [Improvements to the test suites for past and current releases](https://github.com/emberjs/data/issues/5607)
- [Travis Test Job to catch issues with floating dependencies](https://github.com/emberjs/data/pull/5551)
- [Even](https://github.com/emberjs/data/pull/5528) [more tests!](https://github.com/emberjs/data/pull/5533)

In addition to the above, `LinkedIn` has been using the `RecordData` version of the internals in conjunction with [ember-m3](https://github.com/hjdivad/ember-m3) for the past 8 months while we worked to bring it to maturity. While `LinkedIn` does not use all the features of `ember-data`, this has given us reasonable confidence that we're ready for additional external partners to test this new feature.

In order to ensure a smooth transition from the `pre-` to the `post-` `RecordData` world, we will be doing the following:

### Library Next Steps

- [x] Release `3.5.0-beta.2` with the `RecordData` [feature enabled](https://github.com/emberjs/data/pull/5616)
- [x] Unskip and fix the `belongs-to` and `has-many` rendering tests for `RecordData`. (Some refactoring of the `RecordData` version of things may be needed and it may be necessary to write `RecordData` specific versions of these tests). 
- [x] Continue addressing issues surfaced in `3.4` and ensure fixes and tests are applied to both `3.4` and `3.5`
- [ ] Configure BrowserStack for EmberData and ensure IE11 test coverage
- [x] Address any issues surfaced while `RecordData` is in `beta`
- [x] Add "spec tests" for `RecordData` #5653 
- [x] Cleanup anything named `modelData` in favor of `recordData`
- [x] Remove the `pre-RecordData` build path
- [x] Add any additional OS Applications we can to our test suite to ensure wider coverage. (`Ghost`? `UCSF`?)

### Community Next Steps

- Configure your apps/addons to test against ember-data beta
- Report errors encountered, and help triage/replicate as much as possible
- Help with any of the `Library Next Steps` that you can
- Help refactor existing addons to utilize `RecordData` instead of likely-removed intimate APIs (for a good starter list, see our [external-partner tests](https://github.com/emberjs/data/blob/master/.travis.yml#L87-L103)) 

### When will `RecordData` enter Stable Release?

The criteria to advance `RecordData` to a stable release are:

- it is clear that no major issues remain
- that most apps can seamlessly upgrade to it without issue
- the most commonly used community addons support it

**Comment by runspired** [comment]
#5653 has been opened as an additional item needed for the `record-data` feature to mature.
