### ISSUE TITLE
Kill off use of Travis CI

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6282]
We've been running on Azure with a ton of success for a few months now. #6098 if polished off would reach full parity with what we were doing on Travis before, although what we have now is already better.

This ticket can be closed when

- [x] ~#6098~ #6472 is landed
- [x] CI status badge in README is replaced (https://github.com/emberjs/data/pull/6517)
- [x] #6472 is backported to beta branch
- [x] #6472 is backported to release branch
- [x] #6472 is backported to LTS branch
- [x] #6547 The Azure Pipeline config is removed
- [x] The TravisCI job is removed

**Comment by runspired** [comment]
cc @HeroicEric if you have some time to finish this :)

**Comment by dhuang612** [comment]
I would like to work on this!

**Comment by runspired** [comment]
@dhuang612 thanks :) I'll let @HeroicEric lead

**Comment by runspired** [comment]
Allowed fails are now the only remaining use for TravisCI

We can replace this by using a github action plus function to run a test as "allowed to fail" and then leaving a comment on the PR if the allowed scenario did fail with details.
