### ISSUE TITLE
Octane Support Audit

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6527]
- [x] #6143 issue with needing to use @tracked for modelName when using polymorphism
- [x] #6393 `id` needs `@tracked` / `Ember.get` 
- [x] #6728 Mixin based polymorphism fails `detect`

Additionally there have been discord reports / mysterious guidance that folks must use `set` to update properties on EmberData models. Since `attr|belongsTo|hasMany` are based on `@computed` this *should not* be true. However we should make extra certain and verify this:

- [x] ensure EmberData models do not require `get` or `set` (fix if so)
- [x] ensure Octane guides do not say the EmberData models require `get` or `set` (at least one report mentioned reading this in the Octane docs)

**Comment by runspired** [comment]
A thought that just occurred to me, the reason folks think that they have to use `get/set` with EmberData records is because they are likely trying to access properties in their JS code from async relationships without having resolved the value.

We should encourage use of `await` or promise usage in those scenarios.

**Comment by pzuraq** [comment]
Noting down the current state:

* `modelName` should likely become a computed or tracked property on the class itself, with preference to computed so that it will still work with `sync` observers.
* `id` should be converted to a computed for the same reasons, but historically there were issues with it being one. If that's still the case, the alternative would be we to use `get` and `notifyPropertyChange` within the native getter/setter:

```js
import { get, notifyPropertyChange } from '@ember/object';

get id() {
  get(this, '__ID__');

  return ...;
}

set id(value) {
  this.internalId = ...;

  notifyPropertyChange(this, '__ID__');
}
```

Relationships/attrs in general should be good, since they're all CPs. If there are users reporting issues with them, we should dig in.

**Comment by btecu** [comment]
@runspired isn't `set` still required for relationships?

**Comment by pzuraq** [comment]
It should not be. Under the hood, relationships are [computed properties](https://github.com/emberjs/data/blob/master/packages/model/addon/-private/has-many.js#L180). These now install native setters in Ember 3.13+, so it should be fine to treat them as normal properties.

Pushing values in a `hasMany` array still requires KVO update methods, such as `pushObject` and `popObject`, etc.

**Comment by runspired** [comment]
modelName fix is in #6746

**Comment by runspired** [comment]
All known issues are resolved, closing.
