### ISSUE TITLE
[TRACKING] Relationship Refactor

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6573]
Tracking Issue for Improvements to the Performance, Reliability, and Encapsulation of the Relationship Layer.

**Comment by runspired** [comment]
Parallel Efforts that assist this effort (the first three are already tasks for Project Trim)

- [ ] The Singleton RecordData Infrastructure
- [ ] RecordData Documentation
- [ ] A Refactor moving as much relationship UI logic out of internalModel/the store into the Model package as possible
- [ ] A Singleton RecordData Implementation for EmberData

**Comment by runspired** [comment]
cc @sly7-7 This is an effort I'm pairing with @skaterdav85 on to improve relationships that should help you greatly :) If you have the ability to contribute to it to help resolve your performance issues with relationships that would be awesome!

**Comment by skaterdav85** [comment]
👋

**Comment by runspired** [comment]
I removed the Diff util in #8550 which we may end up wanting later. It was currently unused so seemed better to drop for now.

**Comment by runspired** [comment]
The main change I want to see before marking the API as complete is a story around pagination. I began a spike for it in #9320.

The largest unanswered question is what the underlying page storage mechanism should be, and how (with it) to account for the potential for someone to fetch an arbitrary page of the relationship (where arbitrary means that a gap in pages exists between that page and any pages connected to the first or last page).

Pagination is so varied it is necessarily hard to support arbitrary pages (whereas it is relatively easy to support first/prev/next/last as pointers for iteration of a linked list).

Potential data structures include:

- a LinkedList
- a dictionary, holey array keyed by a signaled index
- a Map keyed by a signaled index
- something that keys by url but accounts for indexing
