### ISSUE TITLE
[Proposal] Automated RFC Tracking

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6686]
# Proposal

The following proposal details github actions which if implemented would streamline the process of tracking the implementation status of RFCs.

## For deprecation RFCs

- [ ] enforce RFCs with the T-ember-data & T-deprecation label have an owner to be mergeable
- [ ] enforce RFCs to have `- label: <featureName>`
- [ ] when an RFC with the T-ember-data label is merged, automatically create the RFC Tracking issue, assign the owner, link the RFC test, attach the ember-data and deprecation labels.
- [ ] create a label in EmberData of the form `DEPRECATION-<PR#>-<featureName>`
- [ ] create a card for the feature in https://github.com/emberjs/data/projects/8
  - links the RFC
  - links the tracking issue
  - links the label
  - check boxes for standard action items

```
<featureName> in stable release

- [ ] implementation
- [ ] Deprecation Guide
- [ ] ON in Canary
- [ ] ON in Beta
- [ ] ON in Released version
- [ ] deprecated behavior removed
```

- [ ] when creating a new issue or PR attaching the `DEPRECATION-<PR#>-<featureName>` label should auto assign it to the project

## For feature RFCs

- [ ] enforce RFCs with the T-ember-data label have an owner to be mergeable
- [ ] enforce RFCs to have `- label: <featureName>`
- [ ] when an RFC with the T-ember-data label is merged, automatically create the RFC Tracking issue, assign the owner, link the RFC test, attach the ember-data label.
- [ ] create a label in EmberData of the form `RFC-<PR#>-<featureName>`
- [ ] create a card for the feature in https://github.com/emberjs/data/projects/7
  - links the RFC
  - links the tracking issue
  - links the label
  - check boxes for standard action items

```
<featureName> in stable release

- [ ] implementation
- [ ] API Documentation
- [ ] ON in Canary
- [ ] ON in Beta
- [ ] ON in Released version
- [ ] instrumentation removed
```

- [ ] when creating a new issue or PR attaching the `RFC-<PR#>-<featureName>` label should auto assign it to the project

**Comment by runspired** [comment]
closing in favor of https://github.com/emberjs/rfcs/pull/617
