### ISSUE TITLE
6.0 Roadmap

### ISSUE THREAD

**Issue by runspired** [emberjs/data#8460]
# 6.0 Roadmap

**Target Date:** Fall 2023

## Overview

The **EmberData** Team intends to release a major version of the library around/during the summer of 2023. This issue tracks the work to be done to prepare for that major.

This major version will focus on refining the library for the Polaris Edition by building on the work delivered in 5.0

1. Removal of most remaining support for Ember classic (some bare minimum support may remain until Ember similarly deprecates support)
2. Completing the decoupling EmberData from Ember the framework
3. Introduction of a model-optional default story for presenting data in applications

## Action Items

This is a non-comprehensive list that we expect to grow over the next several months as we determine the exact mechanics of achieving the above.

**Intended Deprecations**

> Note: This list carries forward what we hoped to deprecate for 5.0 but did not complete.

- [ ] deprecate Legacy Imports https://github.com/emberjs/rfcs/pull/743
- [ ] deprecate ajax for fetch https://github.com/emberjs/rfcs/pull/790
- [ ] deprecate non-strict types https://github.com/emberjs/rfcs/pull/740
- [ ] deprecate extending native error https://github.com/emberjs/rfcs/issues/402
- [ ] deprecate missing data for sync relationships being considered empty https://github.com/emberjs/rfcs/issues/360
- [ ] deprecate store normalization/serialization APIs https://github.com/emberjs/rfcs/issues/357
- [ ] deprecate serializer.extractErrors
- [ ] deprecate store.modelFor
- [ ] deprecate Model init / property access during init
- [ ] deprecate setting unknown args on Model
- [ ] deprecate RecordArrays being passed to adapters
- [ ] deprecate null values for collection relationships
- [ ] deprecate accessing values on records post-destroy

**Refactoring**
- [ ] move existing coalescing logic into the adapters
- [ ] return promises from unloadRecord/unloadAll https://github.com/emberjs/rfcs/issues/385

**Getting Started Experience**
- [ ] `npx ember-data` walk-thru setup

**Documentation**
- [ ] Guides Overhaul

**Cache Improvements**
- [ ] introduce operations for delete and relationship updates https://github.com/emberjs/rfcs/issues/355 https://github.com/emberjs/rfcs/pull/458
- [ ] REST/GraphQL Caches and Middleware
  
**Presentation**

- [ ] Model-less EmberData
  - [ ] Collection Primitive
  - [ ] Paginated Collection
  - [ ] Support Nested Relationship Keys
  - [ ] ProxyModel supports nested attributes
  - [ ] schema decorators and schema model for transitioning users
