### ISSUE TITLE
🛤️ tracking: 5.3 Release Checklist

### ISSUE THREAD

**Issue by runspired** [emberjs/data#8743]
> **note**
> This issue originally tracked 5.2, but we opted to push to 5.3 to ensure polish

Implementation notes for the [Roadmap](https://github.com/emberjs/data/blob/main/ROADMAP.md)

# Overview

The primary focus of this release is on utilities to polish the request-builder story.

Ultimately all builders and serialization utils are intended to be compatible with 4.12, for the `JSON:API` version this will require us to provide a temporary alternative package as the existing @ember-data/json-api package cannot be safely added twice to the same app and would need to be. We expect to publish this as `@ember-data/json-api-request`.

## Misc

- [x] Deprecate legacy import paths
- [x] Deprecate non-strict-type
- [x] Deprecate non-strict-id
- [x] Graph Diffing (required for serialization utils)
- Deprecate legacy relationship fixes? (potentially part of implementing diffing)
  - [-] ~deprecate missing being considered empty~ unnecessary for diffing, removed from release goal
  - [x] deprecate fixing non-unique relationship payloads
  - [x] deprecate remote updates clearing local changes
- [x] Refactor @ember-data/model setup/teardown hooks logic to be importable
- [x] [blocker] graph setup should not occur within `ember-data/store`

## If we were dreaming

Improved build infra would allow us to begin publishing some native unstable preview types and some stable ones.

Specifically:

- @ember-data/request (unstable preview)
- @ember-data/rest (stable)
- @ember-data/active-record (stable)
- @ember-data/request-utils (stable)
- @ember-data/tracking (stable)

Additionally the following are close to publishable but their types would be especially unstable:

- @ember-data/json-api (unstable preview)
- @ember-data/graph (unstable preview)

Publishing these would help close gaps with the unofficial DefinitelyTyped types as most of these were never typed there.

**Other if we were dreaming work**

- Pagination & Diffing Utils
- promise-cache (a new render performance primitive for use by ember-promise-helpers and other libraries)

## Relationship Diff Support

  - [x] RelationshipDiff
  - [x] cache.changedRelationships
     - [x] tests
     - [x] API Docs
  - [x] cache.hasChangedRelationships
      - [x] tests
      - [x] API Docs
  - [x] cache.rollbackRelationships
      - [x] tests
      - [x] API Docs

## Request Utils (@ember-data/request-utils)

  - [x] Package Overview
  - [x] Package README

* buildBaseURL
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* buildQueryParams
  - [x] Implemented
  - [x] Tests
  - [x] API Docs

* filterEmpty
  - [x] Implemented
  - [x] Tests
  - [x] API Docs

* sortQueryParams
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* LifetimesService
   - [x] Implemented
   - [ ] Tests
  - [x] API Docs
  
 * setBuildURLConfig
   - [x] Implemented
   - [x] Tests
   - [x] API Docs
   
 * parseCacheControl
   - [x] Implemented
   - [x] Tests
   - [x] API Docs
  

## JSON:API Builders (@ember-data/json-api/request)

  - [x] Package Overview
  - [x] Package README

* findRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs

* query
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* deleteRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* updateRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* createRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs

## REST Builders (@ember-data/rest/request)

  - [x] Package Overview
  - [x] Package README

* findRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
 
* query
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* deleteRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* updateRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* createRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs

## ActiveRecord Builders (@ember-data/active-record/request)

  - [x] Package Overview
  - [x] Package README

* findRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs

* query
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* deleteRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* updateRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
* createRecord
  - [x] Implemented
  - [x] Tests
  - [x] API Docs
  
## JSON:API Serialization Utils

* serializeResources
  - [x] Implemented
  - [x] Tests
  - [x] API Docs

* serializePatch
  - [x] Implemented
  - [x] Tests
  - [x] API Docs

## deprioritized

The below were deprioritized in favor of waiting until their respective Cache implementations
are complete.
  
#### REST Serialization Utils
  
* serializeResources
  - [-] Implemented
  - [-] Tests
  - [-] API Docs

* serializePatch
  - [-] Implemented
  - [-] Tests
  - [-] API Docs
  
#### ActiveRecord Serialization Utils
    
* serializeResources
  - [-] Implemented
  - [-] Tests
  - [-] API Docs

* serializePatch
  - [-] Implemented
  - [-] Tests
  - [-] API Docs

**Comment by kategengler** [comment]
The deprecations need deprecation guides here https://github.com/ember-learn/deprecation-app and URLs to those deprecations added at the invocation site.

**Comment by Baltazore** [comment]
@runspired any way I can help here ?

I also have few questions related to data serialization, that was requested using request-builders, how to push it to store, EmberInspector does not work for me locally as well.
Anyway if there is a place to read more about it point me out please.

**Comment by runspired** [comment]
@Baltazore would you be able to copy the deprecation guide we have in the project and fix it up for the deprecation-app @kategengler linked above? That would be a pretty easy place to start.

**Comment by Baltazore** [comment]
@runspired I assume I have to pull info from this file https://github.com/emberjs/data/blob/b293542d00438d4470075f9b77f74ae58960bf68/packages/private-build-infra/virtual-packages/deprecations.js

Here is PR https://github.com/ember-learn/deprecation-app/pull/1339

**Comment by runspired** [comment]
We've released! <3
