### ISSUE TITLE
tracking: 4.12.x special LTS backporting

### ISSUE THREAD

**Issue by runspired** [emberjs/data#9013]
This ticket tracks work we expect to backport to 4.12, including that mentioned here https://blog.emberjs.com/ember-data-4-12-special-release-update-2023-09-22

- [x] @ember-data/rest builder utils
- [x] @ember-data/active-record builder utils
- [x] @ember-data/request-utils
- [x] @ember-data/json-api/request (potentially as @ember-data/json-api-request) builder utils
- [x] CacheHandler updates
- [x] RequestManager updates
- [x] removal of @ember/runloop usage
