### ISSUE TITLE
🛤️ tracking: The Road to Polaris ✨

### ISSUE THREAD

**Issue by runspired** [emberjs/data#9337]
## 🌌 Universal

> [!NOTE]
> Universal *also* presumes that we ship SchemaRecord (in the WarpDrive section)
> for full utility, and that tasks in the Vite section are done.

- derisk decoupling EmberData from Ember's runloop
  - [ ] (upstream) Render Aware Scheduler RFC

- EmberData without EmberSource
  - [ ] deprecate Store extending EmberObject
  - [ ] hook @ember-data/tracking for arbitrary signal implementations
     - and/or adopt StarbeamJS
     - and/or adopt Reactive Primitives proposal from TC39
  - [ ] replace `@ember/debug` (`assert`, `warn`, `deprecate`) usage with something not tied to ember-source
  - [ ] Configuration point for `@ember/test-waiters` for non-ember projects
  - [ ] replace `@ember/string` usage with something lighter of our own
  
## 🚀 WarpDrive

- SchemaService
  - [ ] RFC SchemaService upgrade needed for SchemaRecord
  - [ ] Ship new implementation with 4.12 support

- Schema DSL
  - Legacy
    - [ ] Can parse simple legacy attributes to JSON schema
    - [ ] Can parse complex legacy attributes to JSON schema
    - [ ] Can parse belongsTo to JSON schema
    - [ ] Can parse hasMany to JSON schema
    - [ ] Can parse ID field to JSON schema
    - [ ] Can parse derived field to JSON schema
    - [ ] Can parse local field to JSON schema
    - [ ] Traits are included in JSON schema
    - [ ] Can parse simple legacy attributes to read Type
    - [ ] Can parse complex legacy attributes to read Type
    - [ ] Can parse belongsTo to read Type
    - [ ] Can parse ID field to read Type
    - [ ] Can parse derived field to read Type
    - [ ] Can parse local field to read Type
    - [ ] Traits are included in read Type
    - [ ] Can parse hasMany to read Type
    - [ ] Can parse simple legacy attributes to update Type
    - [ ] Can parse complex legacy attributes to update Type
    - [ ] Can parse belongsTo to update Type
    - [ ] Can parse hasMany to update Type
    - [ ] Can parse ID field to update Type
    - [ ] Can parse derived field to update Type
    - [ ] Can parse local field to update Type
    - [ ] Traits are included in update Type
    - [ ] Can parse simple legacy attributes to create type
    - [ ] Can parse complex legacy attributes to create Type
    - [ ] Can parse belongsTo to create type
    - [ ] Can parse hasMany to create type
    - [ ] Can parse ID field to create Type
    - [ ] Can parse derived field to create Type
    - [ ] Can parse local field to create Type
    - [ ] Traits are included in create Type
 - Modern
    - [ ] Can parse generic fields to JSON schema
    - [ ] Can parse object fields to JSON schema
    - [ ] Can parse array fields to JSON schema
    - [ ] Can parse schema-object to JSON schema
    - [ ] Can parse schema-array to JSON schema
    - [ ] Can parse resource to JSON schema
    - [ ] Can parse collection to JSON schema
    - [ ] Can parse generic fields to read Type
    - [ ] Can parse object fields to read Type
    - [ ] Can parse array fields to read Type
    - [ ] Can parse schema-object to read Type
    - [ ] Can parse schema-array to read Type
    - [ ] Can parse resource to read Type
    - [ ] Can parse collection to read Type
    - [ ] Can parse generic fields to update Type
    - [ ] Can parse object fields to update Type
    - [ ] Can parse array fields to update Type
    - [ ] Can parse schema-object to update Type
    - [ ] Can parse schema-array to update Type
    - [ ] Can parse resource to update Type
    - [ ] Can parse collection to update Type
    - [ ] Can parse generic fields to create Type
    - [ ] Can parse object fields to create Type
    - [ ] Can parse array fields to create Type
    - [ ] Can parse schema-object to create Type
    - [ ] Can parse schema-array to create Type
    - [ ] Can parse resource to create Type
    - [ ] Can parse collection to create Type

- SchemaRecord

  

## 🐹 Ember

- Ship stable of `@warp-drive/ember`
  - [ ] Instrument legacy promises for eager promise cache population
  - [ ] Implement isBackgroundReloading
  - [ ] Implement backgroundReload abort/retry
  - [ ] Implement autoRefresh
  - [ ] Implement Pagination Utils
  - [ ] Implement Pagination Component

## 🩻 Testing & Debugging

- Mocking
  - Ship stable of `@warp-drive/holodeck`
    - [ ] Make it easy to toggle recording for the entire test-suite
    - [ ] Integrate recording toggle to testem and diagnostic options
    - [ ] Add docs for testem config
    - [ ] fix shutdown bug
  - [ ] http/3 ? (if Bun lands support)
  - [ ] Provide utils and docs around how to functionally compose mock data
        for holodeck
  - [ ] API Route Mocking

- Inspector
  - [ ] Support RequestManager in Inspector
  - [ ] Support SchemaRecord in Inspector
  - [ ] Make it possible to activate logging during development
        without restarting build

## ⚡️ Vite

> [!TIP]
> This section might be one of the easiest to complete for someone that understands
> a bit of tooling without needing to dig into EmberData's library code.

- EmberData without EmberCLI
  - [ ] build config method
  - [ ] ship all packages in v2 format
  - [ ] stand-alone macros plugin for vite

## 💚 Typescript

> [!TIP]
> This section might be one of the easiest to complete for someone that understands
> typescript without needing to learn too much of EmberData's library code.

- [ ] rollup `.d.ts` files to reduce import surface area
- [ ] improve quality of types so we can mark them as stable

## 💡 API Documentation

- 🚧 FILL ME OUT 🚧

## 🔭 Guides

- [ ] Ember Guides rewritten to Polaris EmberData patterns
- [ ] SuperRentals tutorial rewritten to Polaris EmberData patterns
- [ ] Find somewhere to publish the in-repo guides we've written

## 🚢 Onboarding

- `npx warp-drive|ember-data` to run user through a flow that configures packages for them.

**Comment by lifeart** [comment]
Really inspiring list! 

@runspired is any CRDT support planned (https://blog.notmyidea.org/a-comparison-of-javascript-crdts.html)?
@Baltazore said it's could be implemented on top of custom handler

**Comment by runspired** [comment]
@lifeart built-in support for CRDT is not planned, and likely never will be due to how it overlaps with JSON:API operations

**Comment by sandstrom** [comment]
@lifeart If you have some free time, and would like to contribute to this roadmap, we'd be willing to sponsor your work on Ember Data.

Can discuss in more detail if you're interested (we're sponsoring runspired and rwjblue already).

**Comment by runspired** [comment]
a few polaris updates:

- due to time constraints, we won't ship the schema-dsl
- we won't ship store forking
- we won't ship explicit partials (note, most of what folks want from partials works out of the box, explicit partials is a *very* niche feature addition)

**Comment by sandstrom** [comment]
@runspired Do you know anyone involved in Ember Data (Warp drive) that might be interested in sponsorship? I would prefer someone that you'd point to, and of course it would need to be someone that's interested 😄 

I talked with lifeart (comment above), but it wasn't a good fit at the time, due to other things he had ongoing (but our offer still stands for him too, of course).

**Comment by acorncom** [comment]
@sandstrom I've been wanting to dig in on helping Chris with various aspects of the Ember Data / Warp Drive roadmap, but haven't had a client who was interested in helping sponsor things. Can you DM / email me so we can discuss what you need in more detail?

**Comment by NullVoxPopuli** [comment]
Interactive tutorial infra here: https://github.com/NullVoxPopuli/warp-drive-tutorial

**Comment by sandstrom** [comment]
@acorncom Sent you an email via Acorn Web Consultants form.

**Comment by sandstrom** [comment]
@runspired Just wanted to check in on this thread again. Do you know anyone involved in Ember Data / Warp drive that might be interested in sponsorship?

**Comment by runspired** [comment]
@sandstrom I'd recommend anyone on the core team: @gitKrystan @Baltazore @richgt though there's a few others that have been getting more involved of late as well such as @leoeuclids and @MehulKChaudhari.

**Comment by MehulKChaudhari** [comment]
> > I'd recommend anyone on the core team: gitKrystan Baltazore richgt though there's a few others that have been getting more involved of late as well such as leoeuclids and MehulKChaudhari.
> 
> I've added a small monthly sponsorship ($100) for MehulKChaudhari (seemed to be the most active as of late, but if anyone else is interested in the mentioned group, let me know!).
> 
> Thanks for your contributions to warp-drive [@MehulKChaudhari](https://github.com/MehulKChaudhari) and looking forward to follow your work! 😄

@sandstrom Thank you so much for the support 🙏 I really appreciate it, and Glad to contribute and keep learning with WarpDrive team.
