### ISSUE TITLE
Reactivated 4.x Branch Tracking

### ISSUE THREAD

**Issue by runspired** [emberjs/data#9597]
This is a tracking issue for work we intend to do branching from 4.12 that will result in new minor releases in the 4.x series.

Our goals are (in order)

- enable 4.x versions of packages to be consumed by ember apps using vite
- align schema, cache, and request-manager implementations to 5.3+ as much as possible to enable schema-record compatibility
- align typescript signatures as much as possible to ease adoption of native types

Working branch is [v4-main](https://github.com/emberjs/data/tree/v4-main)

### Infrastructure Improvements to Support Extended Release Cycles

- [x] ESLint Flat Config
- [x] Typescript Latest
- [x] TSConfig use References
- [x] V2 Addons
- [x] Config Tooling
- [x] Automated Release Script
- [x] Turborepo Config
- [x] Prettier Config
- [x] Upgrade PNPM
- [x] Port Dependency Patches
- [x] VSCode Settings
